---
- name: Install python3
  apt:
    name: python3
    state: present
    allow_unauthenticated: yes
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    allow_unauthenticated: yes
    state: present