# {{ users }}: List of users
---
- name: Add local users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.desc }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    shell: /bin/bash
    append: yes
    createhome: yes
    expires: -1
    state: present
  with_items: "{{ users }}"

- name: Set local users authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  with_items: "{{ users }}"

- name: Create users known_hosts file
  file:
    path: "/home/{{ item.name }}/.ssh/known_hosts"
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ users }}"
